import fs from 'fs';
import path from 'path';
import type { Plugin } from 'vite';
import { visualizer } from 'rollup-plugin-visualizer';

type EmittedAsset = {
    type: 'asset';
    fileName: string;
    source: string | Uint8Array;
};

type EmittedChunk = {
    type: 'chunk';
    fileName: string;
    isEntry: boolean;
    imports: string[];
    dynamicImports: string[];
    exports: string[];
    code: string;
    modules?: Record<string, unknown>;
};

type EmittedItem = EmittedAsset | EmittedChunk;

export type ReportSection =
    | 'entryChunks'
    | 'dependencyPackages'
    | 'sourceModules'
    | 'shipped'
    | 'visualizer';

const DEFAULT_REPORT_SECTIONS: ReportSection[] = [
    'entryChunks',
    'dependencyPackages',
    'sourceModules',
    'shipped',
    'visualizer',
];

export interface BundleReportOptions {
    /**
     * Output file path for the combined report.
     * Includes emitted chunks/assets, dependency packages, source modules,
     * and raw visualizer data generated by rollup-plugin-visualizer.
     * @example 'dist/dependencies.json'
     */
    dependenciesOutputFile: string;

    /**
     * Report sections to include in the output.
     * Uses canonical keys in the final report (`entryChunks`, `dependencyPackages`, etc).
     * Defaults to all sections.
     */
    reportSections?: ReportSection[];

    /**
     * Absolute path to the project root, used to compute relative source module paths.
     * Defaults to Vite's resolved project root.
     */
    projectRoot?: string;
}

function createBundleReportPlugin(options: BundleReportOptions): Plugin {
    const { dependenciesOutputFile, reportSections, projectRoot } = options;
    let resolvedProjectRoot = projectRoot ?? process.cwd();

    return {
        name: 'vite-plugin-bundle-report',
        apply: 'build',
        configResolved(config) {
            if (!projectRoot) {
                resolvedProjectRoot = config.root;
            }
        },
        async generateBundle(_options: unknown, bundle: Record<string, EmittedItem>) {
            const reportPath = path.resolve(resolvedProjectRoot, dependenciesOutputFile);
            const visualizerTempOutputFile = path.join(
                path.dirname(reportPath),
                `${path.basename(reportPath, path.extname(reportPath))}.visualizer.json`,
            );

            const visualizerPlugin = visualizer({
                filename: visualizerTempOutputFile,
                json: true,
            }) as unknown as {
                generateBundle?: (
                    this: unknown,
                    outputOptions: unknown,
                    outputBundle: Record<string, EmittedItem>,
                    isWrite: boolean,
                ) => void | Promise<void>;
            };

            if (visualizerPlugin.generateBundle) {
                await visualizerPlugin.generateBundle.call(this, _options, bundle, true);
            }

            const emitted = Object.values(bundle).map((item) => {
                if (item.type === 'asset') {
                    const sourceSize =
                        typeof item.source === 'string'
                            ? Buffer.byteLength(item.source)
                            : item.source.byteLength;
                    return {
                        type: 'asset',
                        fileName: item.fileName,
                        size: sourceSize,
                    };
                }

                return {
                    type: 'chunk',
                    fileName: item.fileName,
                    isEntry: item.isEntry,
                    imports: item.imports,
                    dynamicImports: item.dynamicImports,
                    exports: item.exports,
                    size: Buffer.byteLength(item.code),
                };
            });

            const chunks = Object.values(bundle).filter(
                (item): item is EmittedChunk => item.type === 'chunk',
            );
            const moduleIds = chunks.flatMap((chunk) =>
                Object.keys(chunk.modules ?? {}),
            );

            const dependencyPackages = Array.from(
                new Set(
                    moduleIds
                        .map((moduleId) => {
                            const marker = '/node_modules/';
                            const markerIndex = moduleId.lastIndexOf(marker);
                            if (markerIndex === -1) {
                                return null;
                            }

                            const pathAfterNodeModules = moduleId.slice(
                                markerIndex + marker.length,
                            );
                            const nestedNodeModulesIndex =
                                pathAfterNodeModules.lastIndexOf('/node_modules/');
                            const dependencyPath =
                                nestedNodeModulesIndex === -1
                                    ? pathAfterNodeModules
                                    : pathAfterNodeModules.slice(
                                          nestedNodeModulesIndex + '/node_modules/'.length,
                                      );

                            if (dependencyPath.startsWith('@')) {
                                const [scope, name] = dependencyPath.split('/');
                                return scope && name ? `${scope}/${name}` : null;
                            }

                            const [name] = dependencyPath.split('/');
                            return name ?? null;
                        })
                        .filter((dep): dep is string => Boolean(dep)),
                ),
            ).sort();

            const sourceModules = Array.from(
                new Set(
                    moduleIds
                        .map((moduleId) => moduleId.replace(/\\/g, '/'))
                        .filter(
                            (moduleId) =>
                                moduleId.includes('/src/') ||
                                moduleId.startsWith('src/') ||
                                moduleId.startsWith('./src/'),
                        )
                        .map((moduleId) => {
                            if (path.isAbsolute(moduleId)) {
                                return path
                                    .relative(resolvedProjectRoot, moduleId)
                                    .replace(/\\/g, '/');
                            }

                            return moduleId.replace(/^\.\//, '');
                        }),
                ),
            ).sort();

            let visualizerData: unknown = null;
            if (visualizerTempOutputFile && fs.existsSync(visualizerTempOutputFile)) {
                try {
                    visualizerData = JSON.parse(
                        fs.readFileSync(visualizerTempOutputFile, 'utf8'),
                    );
                } catch {
                    visualizerData = null;
                }
            }

            const selectedSections = new Set(reportSections ?? DEFAULT_REPORT_SECTIONS);
            selectedSections.add('entryChunks');

            const dependenciesReport: Partial<Record<ReportSection, unknown>> = {
                entryChunks: chunks
                    .filter((chunk) => chunk.isEntry)
                    .map((chunk) => chunk.fileName),
                dependencyPackages,
                sourceModules,
                shipped: emitted,
                visualizer: visualizerData,
            };

            const filteredDependenciesReport = Object.fromEntries(
                Object.entries(dependenciesReport).filter(([section]) =>
                    selectedSections.has(section as ReportSection),
                ),
            );

            const dependenciesReportPath = path.resolve(
                resolvedProjectRoot,
                dependenciesOutputFile,
            );
            fs.mkdirSync(path.dirname(dependenciesReportPath), { recursive: true });
            fs.writeFileSync(
                dependenciesReportPath,
                JSON.stringify(filteredDependenciesReport, null, 2),
            );

            if (visualizerTempOutputFile && fs.existsSync(visualizerTempOutputFile)) {
                fs.unlinkSync(visualizerTempOutputFile);
            }
        },
    };
}

export function bundleReportPlugin(options: BundleReportOptions): Plugin {
    return createBundleReportPlugin(options);
}
