import fs from 'fs';
import os from 'os';
import path from 'path';
import { randomUUID } from 'crypto';
import type { Plugin } from 'vite';
import { visualizer } from 'rollup-plugin-visualizer';

type EmittedAsset = {
    type: 'asset';
    fileName: string;
    source: string | Uint8Array;
};

type EmittedChunk = {
    type: 'chunk';
    fileName: string;
    isEntry: boolean;
    imports: string[];
    dynamicImports: string[];
    exports: string[];
    code: string;
    modules?: Record<string, unknown>;
};

type EmittedItem = EmittedAsset | EmittedChunk;

export type ReportSection =
    | 'entryChunks'
    | 'dependencyPackages'
    | 'sourceModules'
    | 'shipped'
    | 'visualizer';

const DEFAULT_REPORT_SECTIONS: ReportSection[] = [
    'entryChunks',
    'dependencyPackages',
    'sourceModules',
    'shipped',
    'visualizer',
];

export interface BundleReportOptions {
    /**
     * Output file path for the combined report.
     * Includes emitted chunks/assets, dependency packages, source modules,
     * and raw visualizer data generated by rollup-plugin-visualizer.
     * @example 'dist/dependencies.json'
     */
    dependenciesOutputFile: string;

    /**
     * Report sections to include in the output.
     * Uses canonical keys in the final report (`dependencyPackages`, `sourceModules`, etc).
     * Defaults to all sections.
     *
     * Note: `entryChunks` is always present in the output regardless of this option.
     */
    reportSections?: Exclude<ReportSection, 'entryChunks'>[];

    /**
     * Absolute path to the project root, used to compute relative source module paths.
     * Defaults to Vite's resolved project root.
     */
    projectRoot?: string;
}

function readAndDeleteTempFile(filePath: string): unknown {
    try {
        return JSON.parse(fs.readFileSync(filePath, 'utf8'));
    } catch {
        return null;
    } finally {
        try {
            fs.unlinkSync(filePath);
        } catch {
            // ignore — file may not exist if visualizer did not write it
        }
    }
}

type CollectedBundleData = {
    emitted: unknown[];
    entryChunkFileNames: string[];
    dependencyPackages: string[];
    sourceModules: string[];
};

export function bundleReportPlugin(options: BundleReportOptions): Plugin[] {
    const { dependenciesOutputFile, reportSections, projectRoot } = options;
    let resolvedProjectRoot = projectRoot ?? process.cwd();

    // Use os.tmpdir() with a per-invocation UUID so concurrent builds
    // (e.g. multi-config Vite builds) never share the same temp file.
    const visualizerTempFile = path.join(
        os.tmpdir(),
        `vite-plugin-bundle-report-${randomUUID()}.json`,
    );

    let collectedData: CollectedBundleData | null = null;

    const reportPlugin: Plugin = {
        name: 'vite-plugin-bundle-report',
        apply: 'build',
        configResolved(config) {
            if (!projectRoot) {
                resolvedProjectRoot = config.root;
            }
        },
        generateBundle(_options: unknown, bundle: Record<string, EmittedItem>) {
            const emitted = Object.values(bundle).map((item) => {
                if (item.type === 'asset') {
                    const sourceSize =
                        typeof item.source === 'string'
                            ? Buffer.byteLength(item.source)
                            : item.source.byteLength;
                    return {
                        type: 'asset',
                        fileName: item.fileName,
                        size: sourceSize,
                    };
                }

                return {
                    type: 'chunk',
                    fileName: item.fileName,
                    isEntry: item.isEntry,
                    imports: item.imports,
                    dynamicImports: item.dynamicImports,
                    exports: item.exports,
                    size: Buffer.byteLength(item.code),
                };
            });

            const chunks = Object.values(bundle).filter(
                (item): item is EmittedChunk => item.type === 'chunk',
            );
            const moduleIds = chunks.flatMap((chunk) =>
                Object.keys(chunk.modules ?? {}),
            );

            const dependencyPackages = Array.from(
                new Set(
                    moduleIds
                        .map((moduleId) => {
                            const marker = '/node_modules/';
                            const markerIndex = moduleId.lastIndexOf(marker);
                            if (markerIndex === -1) {
                                return null;
                            }

                            const pathAfterNodeModules = moduleId.slice(
                                markerIndex + marker.length,
                            );
                            const nestedNodeModulesIndex =
                                pathAfterNodeModules.lastIndexOf('/node_modules/');
                            const dependencyPath =
                                nestedNodeModulesIndex === -1
                                    ? pathAfterNodeModules
                                    : pathAfterNodeModules.slice(
                                          nestedNodeModulesIndex + '/node_modules/'.length,
                                      );

                            if (dependencyPath.startsWith('@')) {
                                const [scope, name] = dependencyPath.split('/');
                                return scope && name ? `${scope}/${name}` : null;
                            }

                            const [name] = dependencyPath.split('/');
                            return name ?? null;
                        })
                        .filter((dep): dep is string => Boolean(dep)),
                ),
            ).sort();

            const sourceModules = Array.from(
                new Set(
                    moduleIds
                        .map((moduleId) => moduleId.replace(/\\/g, '/'))
                        .filter(
                            (moduleId) =>
                                moduleId.includes('/src/') ||
                                moduleId.startsWith('src/') ||
                                moduleId.startsWith('./src/'),
                        )
                        .map((moduleId) => {
                            if (path.isAbsolute(moduleId)) {
                                return path
                                    .relative(resolvedProjectRoot, moduleId)
                                    .replace(/\\/g, '/');
                            }

                            return moduleId.replace(/^\.\//, '');
                        }),
                ),
            ).sort();

            collectedData = {
                emitted,
                entryChunkFileNames: chunks
                    .filter((chunk) => chunk.isEntry)
                    .map((chunk) => chunk.fileName),
                dependencyPackages,
                sourceModules,
            };
        },
        closeBundle() {
            if (!collectedData) {
                return;
            }

            const { emitted, entryChunkFileNames, dependencyPackages, sourceModules } =
                collectedData;
            collectedData = null;

            const visualizerData = fs.existsSync(visualizerTempFile)
                ? readAndDeleteTempFile(visualizerTempFile)
                : null;

            const selectedSections = new Set<ReportSection>(reportSections ?? DEFAULT_REPORT_SECTIONS);
            selectedSections.add('entryChunks');

            const dependenciesReport: Partial<Record<ReportSection, unknown>> = {
                entryChunks: entryChunkFileNames,
                dependencyPackages,
                sourceModules,
                shipped: emitted,
                visualizer: visualizerData,
            };

            const filteredDependenciesReport = Object.fromEntries(
                Object.entries(dependenciesReport).filter(([section]) =>
                    selectedSections.has(section as ReportSection),
                ),
            );

            const dependenciesReportPath = path.resolve(
                resolvedProjectRoot,
                dependenciesOutputFile,
            );
            fs.mkdirSync(path.dirname(dependenciesReportPath), { recursive: true });
            fs.writeFileSync(
                dependenciesReportPath,
                JSON.stringify(filteredDependenciesReport, null, 2),
            );
        },
    };

    return [
        visualizer({ filename: visualizerTempFile, json: true }) as Plugin,
        reportPlugin,
    ];
}
